CREATE (sitcom:Genre {name: "Sitcom"})
CREATE (surreal:Genre {name: "Surreal"})
CREATE (aa:Genre {name: "Action-Adventure"})
CREATE (fantasy:Genre {name: "Fantasy"})

CREATE (bbt:Show {title: "Big Bang Theory", released: "24/09/2007", ended: "16/05/2019", episodes: 279, photo: "https://upload.wikimedia.org/wikipedia/commons/1/13/TBBT_logo.svg"})
CREATE (fg:Show {title: "Family Guy", released: "01/05/2005", ended: "", episodes: 400, photo: "https://en.wikipedia.org/wiki/Family_Guy#/media/File:Family_Guy_Logo.svg"})
CREATE (pp:Show {title: "Phineas and Ferb", released: "01/02/2008", ended: "12/06/2015", episodes: 129, photo: "https://upload.wikimedia.org/wikipedia/en/6/6e/Phineas_and_Ferb_logo.svg"})
CREATE (atla:Show {title: "Avatar: The Last Airbender", released: "01/02/2005", ended: "01/07/2008", episodes: 61, photo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Avatar_The_Last_Airbender_logo.svg"})
CREATE (slzc:Show {title: "The Suite Life of Zack & Cody", released: "18/03/2005", ended: "25/03/2011", episodes: 87, photo: "https://upload.wikimedia.org/wikipedia/en/8/88/The_Suite_Life_of_Zack_%26_Cody_logo.png"})
CREATE (dp:Show {title: "The Dragon Prince", released: "14/10/2018", ended: "", episodes: 36, photo: "https://upload.wikimedia.org/wikipedia/en/2/2d/The_Dragon_Prince.jpg"})

CREATE (bbt)-[:BELONGS]->(sitcom)
CREATE (fg)-[:BELONGS]->(sitcom)
CREATE (pp)-[:BELONGS]->(surreal)
CREATE (atla)-[:BELONGS]->(aa)
CREATE (slzc)-[:BELONGS]->(sitcom)
CREATE (dp)-[:BELONGS]->(fantasy)

CREATE (mark:Person {name: "Mark", surname: "Cendrowski", born: 1959, photo: "https://static.wikia.nocookie.net/bigbangtheory/images/1/1e/Mark_Cendrowski.png/revision/latest?cb=20220820223514"})
CREATE (jim:Person {name: "Jim", surname: "Parsons", born: 1973, photo: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Jim_Parsons_2016.jpg"})
CREATE (kaley:Person {name: "Kaley", surname: "Cuoco", born: 1985, photo: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Kaley_Cuoco_by_Gage_Skidmore.jpg"})
CREATE (seth:Person {name: "Seth", surname: "MacFarlane", born: 1973, photo: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Seth_MacFarlane_2012_2_cropped_and_retouched.jpg"})
CREATE (dan:Person {name: "Dan", surname: "Povenmire", born: 1963, photo: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Dan_Povenmire_2013_San_Diego_Comic-Con_%28Cropped%29.png"})
CREATE (jeff:Person {name: "Jeffrey", surname: "Marsh", born: 1960, photo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Jeff_%22Swampy%22_Marsh_%28cropped%29.jpg"})
CREATE (michael:Person {name: "Michael", surname: "DiMartino", born: 1974, photo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Dante_DiMartino_by_Gage_Skidmore_2.jpg"})
CREATE (bryan:Person {name: "Bryan", surname: "Konietzko", born: 1976, photo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Bryan_Konietzko_by_Gage_Skidmore_2.jpg"})
CREATE (cole:Person {name: "Cole", surname: "Sprouse", born: 1992, photo: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Cole_Sprouse_%2848478678751%29_%28cropped%29.jpg"})
CREATE (brenda:Person {name: "Brenda", surname: "Song", born: 1988, photo: "https://upload.wikimedia.org/wikipedia/commons/8/88/Brenda_Song_2009_%28Cropped%29.jpg"})
CREATE (aaron:Person {name: "Aaron", surname: "Ehasz", born: 1973, photo: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Aaron_Ehasz_%288220584965%29_%28cropped%29.jpg"})

CREATE (nihao:User {nick: "nihao1170", e_mail: "nihao1170@example.com", password: "123", registered: "17/12/2022", photo: "https://static.wikia.nocookie.net/disney/images/7/74/Bobbi_Fabulous.jpg/revision/latest?cb=20120610215557"})
CREATE (ninja:User {nick: "greenNinja4450", e_mail: "ninjaski@example.com", password: "pass", registered: "13/08/2021", photo: ""})
CREATE (bibi:User {nick: "bibiGO1471", e_mail: "bilbo@example.com", password: "qwerty", registered: "22/11/2022", photo: "https://i.ytimg.com/vi/ubynOv3VKB8/maxresdefault.jpg"})
CREATE (chonk:User {nick: "LeChonk5240", e_mail: "chunker@example.com", password: "emperor", registered: "13/04/2021", photo: ""})
CREATE (ax:User {nick: "axolotusss3230", e_mail: "amphibious@example.com", password: "froggo", registered: "18/03/2020", photo: "https://i.etsystatic.com/19562633/r/il/9d1af6/3148075444/il_570xN.3148075444_tgdf.jpg"})
